export let cards = [
    ["Alulértékelt zenész", "Túlértékelt zenész"],
    ["Erény", "Hiba"],
    ["Könnyű megölni", "Nehéz megölni"],
    ["Megbízhatatlan", "Megbízható"],
    ["Rossz ízű", "Jó ízű"],
    ["Sport", "Játék"],
    ["Munka", "Karrier"],
    ["Lassan történik", "Hirtelen történik"],
    ["Jobb melegen", "Jobb hidegen"],
    ["Szögletes", "Kerek"],
    ["A könyv jobb volt", "A film jobb volt"],
    ["Introvertált", "Extrovertált"],
    ["Barát", "Ellenség"],
    ["Népszerűtlen", "Népszerű"],
    ["Menő", "Nem menő"],
    ["Legrosszabb élő személy", "Legjobb élő személy"],
    ["Osztott", "Egész"],
    ["Népszerűtlen tevékenység", "Népszerű tevékenység"],
    ["Nem szendvics", "Szendvics"],
    ["Rosszul elkészített", "Jól elkészített"],
    ["Alulértékelt színész", "Túlértékelt színész"],
    ["Sötét", "Világos"],
    ["Menza", "Szakácsművészet"],
    ["Puha", "Kemény"],
    ["Kultúrálisan jelentős", "Kultúrálisan jelentéktelen"],
    ["Veszélyes", "Biztonságos"],
    ["Büdös", "Illatos"],
    ["Star Wars", "Star Trek"],
    ["Szellemi tevékenység", "Fizikai tevékenység"],
    ["Vitathatatlan téma", "Vitás téma"],
    ["Jelentős történelmi esemény", "Jelentéktelen történelmi esemény"],
    ["Szőrtelen", "Szőrös"],
    ["Haszontalan testrész", "Hasznos testrész"],
    ["Felkapott", "Klasszikus"],
    ["Unalmas hobbi", "Izgalmas hobbi"],
    ["Etikátlan", "Etikus"],
    ["Az év legrosszabb napja", "Az év legjobb napja"],
    ["Jó", "Gonosz"],
    ["Alulértékelt", "Túlértékelt"],
    ["Maszatos étel", "Tiszta étel"],
    ["Ingatag", "Stabil"],
    ["Kerek állat", "Hegyes állat"],
    ["Gyerekeknek", "Felnőtteknek"],
    ["Vészhelyzetben haszontalan", "Vészhelyzetben hasznos"],
    ["Könnyű téma", "Nehéz téma"],
    ["Ismeretlen", "Híres"],
    ["Ehető", "Nem ehető"],
    ["Mozi", "Tévé"],
    ["A legkevésbé gonosz vállalat", "A leggonoszabb vállalat"],
    ["Nassolás", "Étkezés"],
    ["Alábecsült fegyver", "Túlbecsült fegyver"],
    ["Olcsó", "Drága"],
    ["Gusztustalan reggeli", "Finom reggeli"],
    ["Gyenge", "Erős"],
    ["Szükségtelen", "Szükséges"],
    ["Rossz érzés", "Jó érzés"],
    ["Unalmas", "Izgalmas"],
    ["Rossz szagú", "Jó szagú"],
    ["Szeretett", "Gyűlölt"],
    ["Az erő világos oldala", "Az erő sötét oldala"],
    ["Veszélyes munka", "Biztonságos munka"],
    ["Fantasy", "Sci-fi"],
    ["Átmeneti", "Állandó"],
    ["Személynek néz ki", "Nem néz ki személynek"],
    ["Hihetetlen", "Hihető"],
    ["Vacak", "Príma"],
    ["Közismert", "Ismeretlen"],
    ["Ijesztő állat", "Aranyos állat"],
    ["Környezet", "Nevelés"],
    ["Értéktelen", "Értékes"],
    ["Példakép", "Rossz példa"],
    ["Haszontalan szakma", "Hasznos szakma"],
    ["Békés", "Harcias"],
    ["Alulértékelt film", "Túlértékelt film"],
    ["Durva", "Sima"],
    ["Rossz neked", "Jó neked"],
    ["Kézműves", "Sorozatgyártott"],
    ["Ostoba", "Zseniális"],
    ["Normális", "Furcsa"],
    ["Meleg", "Hideg"],
    ["Unalmas téma", "Izgalmas téma"],
    ["Íztelen", "Ízes"],
    ["Szabadségharcos", "Terrorista"],
    ["Divatjamúlt", "Divatos"],
    ["Macskarajongó", "Kutyabarát"],
    ["Rossz szokás", "Jó szokás"],
    ["Egyenes", "Görbe"],
    ["Normális tulajdon", "Furcsa tulajdon"],
    ["Száraz étel", "Nedves étel"],
    ["Szükség", "Vágy"],
    ["Csúnya állat", "Szép állat"],
    ["Rossz minőségű", "Jó minőségű"],
    ["Átlagos", "Rendkívüli"],
    ["Nehezen kiejthető", "Könnyen kiejthető"],
    ["Csendes hely", "Zajos hely"],
    ["Komédia", "Dráma"],
    ["Nehezen megtalálható", "Könnyen megtalálható"],
    ["Csúnya ember", "Szép ember"],
    ["Helyettesíthető", "Pótolhatatlan"],
    ["Minden idők legrosszabb sportolója", "Minden idők legjobb sportolója"],
    ["Alacsony kalóriatartalmú", "Magas kalóriatartalmú"],
    ["Színtelen", "Színes"],
    ["Törékeny", "Tartós"],
    ["Okostojás", "Tökfej"],
    ["Tehetségtelen", "Tehetséges"],
    ["Bűnös élvezet", "Tiszta szeretet"],
    ["Szomorú film", "Vidám film"],
    ["Idő vesztegetése", "Jó időtöltés"],
    ["Száraz", "Nedves"],
    ["Alábecsült képesség", "Túlbecsült képesség"],
    ["Alkalmi", "Hivatalos"],
    ["Alulfizetett", "Túlfizetett"],
    ["Választható", "Kötelező"],
    ["Alulértékelt betű az ábécében", "Túlértékelt betű az ábécében"],
    ["Egészségtelen", "Egészséges"],
    ["Rossz ember", "Jó ember"],
    ["Ritka", "Gyakori"],
    ["Átlagos emoji", "Szexi emoji"],
    ["Haszontalan találmány", "Hasznos találmány"],
    ["Liberális", "Konzervatív"]
]

export let advancedCards = [
    ["Túl kicsi", "Túl nagy"],
    ["Titkos", "Köztudott"],
    ["Tik", "Tak"],
    ["Rossz tanács", "Jó tanács"],
    ["Hagyományos", "Radikális"],
    ["Rossz édesség", "Jó édesség"],
    ["Illegális", "Legális"],
    ["Rossz szájízt kelt", "Jó szájízt kelt"],
    ["Neked hasznos", "Mindenkinek hasznos"],
    ["Unalmas szín", "Izgalmas szín"],
    ["Sosem időben", "Mindig időben"],
    ["Nem él 100 éves koráig", "100 éves koráig él"],
    ["Mély gondolat", "Felületes gondolat"],
    ["Rossz iskola", "Jó iskola"],
    ["Véges", "Végtelen"],
    ["Alkalmi rendezvény", "Hivatalos rendezvény"],
    ["Rossz befektetés", "Jó befektetés"],
    ["Csevegés", "Komoly beszélgetés"],
    ["Nem egyedi", "Egyedi"],
    ["Korcs", "Fajtiszta"],
    ["Tehetség", "Képesség"],
    ["Legrosszabb időszak időutazóknak", "Legjobb időszak időutazóknak"],
    ["Veszélyeztetett faj", "Túlnépesedett faj"],
    ["Kék", "Zöld"],
    ["A történelem legrosszabb éve", "A történelem legjobb éve"],
    ["Rövid", "Hosszú"],
    ["Természetellenes", "Természetes"],
    ["Őszinte", "Képmutató"],
    ["Borzongató", "Rémisztő"],
    ["Kocka", "Sportos"],
    ["Várható", "Váratlan"],
    ["Személy, akit meg tudnál verni", "Személy, aki meg tudna verni"],
    ["Fóbia", "Félelem"],
    ["Alulértékelt játék", "Túlértékelt játék"],
    ["Enyhe", "Fűszeres"],
    ["Vallásos", "Szentségtörő"],
    ["Furcsa", "Szokatlan"],
    ["Rossz elnök", "Jó elnök"],
    ["Irányíthatatlan", "Irányított"],
    ["Népszerű", "Elitista"],
    ["Mozdulatlan", "Mozgó"],
    ["Helyi probléma", "Globális probléma"],
    ["Utánzat", "Eredeti"],
    ["Etikett", "Stílus"],
    ["Kutyanév", "Macskanév"],
    ["Elfogulatlan", "Fanatikus"],
    ["Gyümölcs", "Zöldség"],
    ["Tudomány", "Áltudomány"],
    ["Nem ölelhető", "Ölelhető"],
    ["Heterogén", "Homogén"],
    ["Rossz Disney-szereplő", "Jó Disney-szereplő"],
    ["Hasonló", "Egyforma"],
    ["Igaz", "Hamis"],
    ["Ódivatú", "Újító"],
    ["Egyslágeres előadó", "Sztár"],
    ["Művészi", "Kommersz"],
    ["Alulértékelt könyv", "Túlértékelt könyv"],
    ["Unalmas személy", "Vicces személy"],
    ["Kicsi", "Apró"],
    ["Csúnya szó", "Gyönyörű szó"],
    ["Sokak számára ismeretlen tény", "Ismert tény"],
    ["Szocializmus", "Kapitalizmus"],
    ["Csendes", "Hangos"],
    ["Átlagos Pokémon", "Szexi Pokémon"],
    ["Bizonytalan", "Határozott"],
    ["Vicces téma", "Komoly téma"],
    ["Legrosszabb házimunka", "Legjobb házimunka"],
    ["Bölcsesség", "Félreértés"],
    ["Kis szám", "Nagy szám"],
    ["Legrosszabb", "Legjobb"],
]
