export let cards = [
    ["Alulértékelt zenész", "Túlértékelt zenész"],
    ["Erény", "Hiba"],
    ["Könnyű megölni", "Nehéz megölni"],
    ["Megbízhatatlan", "Megbízható"],
    ["Rossz ízű", "Jó ízű"],
    ["Sport", "Játék"],
    ["Munka", "Karrier"],
    ["Lassan történik", "Hirtelen történik"],
    ["Jobb melegen", "Jobb hidegen"],
    ["Szögletes", "Kerek"],
    ["A könyv jobb volt", "A film jobb volt"],
    ["Introvertált", "Extrovertált"],
    ["Barát", "Ellenség"],
    ["Népszerűtlen", "Népszerű"],
    ["Menő", "Nem menő"],
    ["Legrosszabb élő személy", "Legjobb élő személy"],
    ["Osztott", "Egész"],
    ["Népszerűtlen tevékenység", "Népszerű tevékenység"],
    ["Nem szendvics", "Szendvics"],
    ["Rosszul elkészített", "Jól elkészített"],
    ["Alulértékelt színész", "Túlértékelt színész"],
    ["Sötét", "Világos"],
    ["Menza", "Szakácsművészet"],
    ["Puha", "Kemény"],
    ["Kultúrálisan jelentős", "Kultúrálisan jelentéktelen"],
    ["Veszélyes", "Biztonságos"],
    ["Büdös", "Illatos"],
    ["Star Wars", "Star Trek"],
    ["Szellemi tevékenység", "Fizikai tevékenység"],
    ["Vitathatatlan téma", "Vitás téma"],
    ["Jelentős történelmi esemény", "Jelentéktelen történelmi esemény"],
    ["Szőrtelen", "Szőrös"],
    ["Haszontalan testrész", "Hasznos testrész"],
    ["Felkapott", "Klasszikus"],
    ["Unalmas hobbi", "Izgalmas hobbi"],
    ["Etikátlan", "Etikus"],
    ["Az év legrosszabb napja", "Az év legjobb napja"],
    ["Jó", "Gonosz"],
    ["Alulértékelt", "Túlértékelt"],
    ["Maszatos étel", "Tiszta étel"],
    ["Ingatag", "Stabil"],
    ["Kerek állat", "Hegyes állat"],
    ["Gyerekeknek", "Felnőtteknek"],
    ["Vészhelyzetben haszontalan", "Vészhelyzetben hasznos"],
    ["Könnyű téma", "Nehéz téma"],
    ["Ismeretlen", "Híres"],
    ["Ehető", "Nem ehető"],
    ["Mozi", "Tévé"],
    ["A legkevésbé gonosz vállalat", "A leggonoszabb vállalat"],
    ["Nassolás", "Étkezés"],
    ["Alábecsült fegyver", "Túlbecsült fegyver"],
    ["Olcsó", "Drága"],
    ["Gusztustalan reggeli", "Finom reggeli"],
    ["Gyenge", "Erős"],
    ["Szükségtelen", "Szükséges"],
    ["Rossz érzés", "Jó érzés"],
    ["Unalmas", "Izgalmas"],
    ["Rossz szagú", "Jó szagú"],
    ["Szeretett", "Gyűlölt"],
    ["Az erő világos oldala", "Az erő sötét oldala"],
    ["Veszélyes munka", "Biztonságos munka"],
    ["Fantasy", "Sci-fi"],
    ["Átmeneti", "Állandó"],
    ["Személynek néz ki", "Nem néz ki személynek"],
    ["Hihetetlen", "Hihető"],
    ["Vacak", "Príma"],
    ["Közismert", "Ismeretlen"],
    ["Ijesztő állat", "Aranyos állat"],
    ["Környezet", "Nevelés"],
    ["Értéktelen", "Értékes"],
    ["Példakép", "Rossz példa"],
    ["Haszontalan szakma", "Hasznos szakma"],
    ["Békés", "Harcias"],
    ["Alulértékelt film", "Túlértékelt film"],
    ["Durva", "Sima"],
    ["Rossz neked", "Jó neked"],
    ["Kézműves", "Sorozatgyártott"],
    ["Ostoba", "Zseniális"],
    ["Normális", "Furcsa"],
    ["Meleg", "Hideg"],
    ["Unalmas téma", "Izgalmas téma"],
    ["Íztelen", "Ízes"],
    ["Szabadségharcos", "Terrorista"],
    ["Divatjamúlt", "Divatos"],
    ["Macskarajongó", "Kutyabarát"],
    ["Rossz szokás", "Jó szokás"],
    ["Egyenes", "Görbe"],
    ["Normális tulajdon", "Furcsa tulajdon"],
    ["Száraz étel", "Nedves étel"],
    ["Szükség", "Vágy"],
    ["Csúnya állat", "Szép állat"],
    ["Rossz minőségű", "Jó minőségű"],
    ["Átlagos", "Rendkívüli"],
    ["Nehezen kiejthető", "Könnyen kiejthető"],
    ["Csendes hely", "Zajos hely"],
    ["Komédia", "Dráma"],
    ["Nehezen megtalálható", "Könnyen megtalálható"],
    ["Csúnya ember", "Szép ember"],
    ["Helyettesíthető", "Pótolhatatlan"],
    ["Minden idők legrosszabb sportolója", "Minden idők legjobb sportolója"],
    ["Alacsony kalóriatartalmú", "Magas kalóriatartalmú"],
    ["Színtelen", "Színes"],
    ["Törékeny", "Tartós"],
    ["Okostojás", "Tökfej"],
    ["Tehetségtelen", "Tehetséges"],
    ["Bűnös élvezet", "Tiszta szeretet"],
    ["Szomorú film", "Vidám film"],
    ["Idő vesztegetése", "Jó időtöltés"],
    ["Száraz", "Nedves"],
    ["Alábecsült képesség", "Túlbecsült képesség"],
    ["Alkalmi", "Hivatalos"],
    ["Alulfizetett", "Túlfizetett"],
    ["Választható", "Kötelező"],
    ["Alulértékelt betű az ábécében", "Túlértékelt betű az ábécében"],
    ["Egészségtelen", "Egészséges"],
    ["Rossz ember", "Jó ember"],
    ["Ritka", "Gyakori"],
    ["Átlagos emoji", "Szexi emoji"],
    ["Haszontalan találmány", "Hasznos találmány"],
    ["Liberális", "Konzervatív"]
]
